# -*- coding: UTF-8 -*-

d_url = 'https://www.usgbc.org/sites/default/files/data/PublicLEEDProjectDirectory.xls'

usecols = ['ID',
'Isconfidential',
'ProjectName',
'City',
'State',
'Country',
'LEEDSystemVersionDisplayName',
'PointsAchieved',
'CertLevel',
'CertDate',
'IsCertified',
'OwnerTypes',
'GrossSqFoot',
'TotalPropArea',
'ProjectTypes',
'RegistrationDate'
]

leed_ver_convert_dict = {
    'LEED v4.1 Residential: Multifamily':'LEED HOMES v4.1',
    'LEED-ND Project Registration 1.0':'LEED ND v1',
    'LEED-ND v2009 Stage 1':'LEED ND 2009',
    'LEED-ND v2009 Stage 2':'LEED ND 2009',
    'LEED-ND v2009 Stage 3':'LEED ND 2009',
    'LEED v4.1 BD+C: CS':'LEED NC/CS v4.1',
    'LEED v4.1 BD+C: NC':'LEED NC/CS v4.1',
    'LEED v4.1 BD+C: HC':'LEED NC/CS v4.1',
    'LEED v4.1 BD+C: SC':'LEED NC/CS v4.1',
    'LEED v4.1 BD+C: WDC':'LEED NC/CS v4.1',
    'LEED v4 BD+C: CS':'LEED NC/CS v4',
    'LEED v4 BD+C: NC':'LEED NC/CS v4',
    'LEED v4 BD+C: HC':'LEED NC/CS v4',
    'LEED v4 BD+C: SC':'LEED NC/CS v4',
    'LEED v4 BD+C: DC':'LEED NC/CS v4',
    'LEED v4 BD+C: WDC':'LEED NC/CS v4',
    'LEED v4 BD+C: HP':'LEED NC/CS v4',
    'LEED v4 BD+C: Retail':'LEED NC/CS v4',
    'LEED v4 BD+C: Transit':'LEED NC/CS v4',
    'LEED Master Site BD+C':'LEED MS',
    'LEED-NC 2.0':'LEED NC/CS v2',
    'LEED-NC 2.1':'LEED NC/CS v2',
    'LEED-NC 2.2':'LEED NC/CS v2',
    'LEED-CS 2.0':'LEED NC/CS v2',
    'LEED for Schools':'LEED NC/CS v2',
    'LEED-NC 1.0 Pilot':'LEED NC/CS v1',
    'LEED-CS 1.0 Pilot':'LEED NC/CS v1',
    'LEED for Retail (New Construction) Pilot':'LEED NC/CS v1',
    'LEED for Retail (NC)':'LEED NC/CS v1',
    'LEED-NC v2009':'LEED NC/CS 2009',
    'LEED-NC Retail v2009':'LEED NC/CS 2009',
    'LEED FOR SCHOOLS v2009':'LEED NC/CS 2009',
    'LEED-CS v2009':'LEED NC/CS 2009',
    'LEED-HC v2009':'LEED NC/CS 2009',
    'LEED-HOMES MR v2010':'LEED HOMES 2010',
    'LEED-HOMES v2008':'LEED HOMES 2008',
    'LEED V4 BD+C: HOLR':'LEED HOMES v4',
    'LEED V4 BD+C: HOMR':'LEED HOMES v4',
    'LEED For Homes Multi Family Low-Rise':'LEED HOMES v4',
    'LEED v4.1 O+M: EB':'LEED EB v4.1',
    'LEED v4.1 O+M: Interiors':'LEED EB v4.1',
    'LEED v4 O+M: EB':'LEED EB v4',
    'LEED v4 O+M: EB WP':'LEED EB v4',
    'LEED v4 O+M: SC':'LEED EB v4',
    'LEED v4 O+M: WDC':'LEED EB v4',
    'LEED v4 O+M: DC':'LEED EB v4',
    'LEED v4 O+M: HP':'LEED EB v4',
    'LEED v4 O+M: Retail':'LEED EB v4',
    'LEED v4 O+M: MF':'LEED EB v4',
    'LEED EB Performance Pilot':'LEED EB v4',
    'LEED v4 O+M: Transit':'LEED EB v4',
    'LEED V4 O+M: EB WP':'LEED EB v4',
    'LEED-EB 2.0':'LEED EB v2',
    'LEED-EB 1.0 Pilot (original)':'LEED EB v1',
    'LEED-EB O&M':'LEED EB v1',
    'LEED-EB 1.0 Pilot':'LEED EB v1',
    'LEED-EB:OM v2009':'LEED EB 2009',
    'LEED v4.1 Communities: Plan and Design':'LEED Communities v4.1',
    'LEED v4.1 Communities: Existing':'LEED Communities v4.1',
    'LEED for Communities':'LEED Communities v4',
    'LEED v4.1 Cities: Exisiting':'LEED Cities v4.1',
    'LEED v4.1 Cities: Plan and Design':'LEED Cities v4.1',
    'LEED for Cities':'LEED Cities v4',
    'LEED v4.1 ID+C: CI':'LEED CI v4.1',
    'LEED v4.1 ID+C: Retail':'LEED CI v4.1',
    'LEED v4 ID+C: CI':'LEED CI v4',
    'LEED v4 ID+C: Retail':'LEED CI v4',
    'LEED v4 ID+C: HP':'LEED CI v4',
    'LEED-CI 2.0':'LEED CI v2',
    'LEED-CI 2.0 Certification (original)':'LEED CI v2',
    'LEED for Retail (CI) Pilot':'LEED CI v1',
    'LEED-CI 1.0 Pilot (original)':'LEED CI v1',
    'LEED-CI 1.0 Pilot':'LEED CI v1',
    'LEED-CI v2009':'LEED CI 2009',
    'LEED-CI Retail v2009':'LEED CI 2009'
}

city_mapping = {
    'shanghai': 'Shanghai'
}

city_geometry = {
    'Shanghai': '31,24',
    'Beijing': '123'
}
